version: '3.7'

volumes:
  db:

services:
  api:
    build: ./app
    ports:
      - "8081:8081"
    networks:
      - shared-network
  
  database:
    image: "postgres"
    container_name: db
    env_file:
      - env/database.env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/
    networks:
      - shared-network
    restart: always

networks:
  shared-network: